apiVersion: v1
kind: Namespace
metadata:
  name: locust-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locust-operator
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","create","update","patch","delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["locust.cloud"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locust-operator-sa
  namespace: locust-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: locust-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: locust-operator
subjects:
- kind: ServiceAccount
  name: locust-operator-sa
  namespace: locust-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-operator
  namespace: locust-operator
  labels:
    app.kubernetes.io/name: locust-operator
    app.kubernetes.io/instance: locust-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: locust-operator
    app.kubernetes.io/created-by: locust-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust-operator
  template:
    metadata:
      labels:
        name: locust-operator
    spec:
      containers:
      - name: locust-operator
        # TODO
        image: ...
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        # TODO
        resources:
          requests:
            cpu: 100m
            memory: 1M
          limits:
            cpu: 100m
            memory: 1M
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 2
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: locust-operator-sa