apiVersion: v1
kind: ServiceAccount
metadata:
  name: locust-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locust-operator
rules:
- apiGroups: [""]
  resources: ["services","configmaps"]
  verbs: ["get","create","update","patch","delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","create","update","patch","delete"]
- apiGroups: ["locust.cloud"]
  resources: ["locusttests","locusttests/status"]
  verbs: ["get","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: locust-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: locust-operator
subjects:
- kind: ServiceAccount
  name: locust-operator
  namespace: default
