{{- if and .Values.rbac.create (not .Values.rbac.cluster) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "locust-operator.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  {{- include "locust-operator.rbacRules" . | nindent 2 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "locust-operator.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "locust-operator.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "dask_kubernetes_operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
