apiVersion: v2
name: locust-operator
description: Locust Operator Helm Chart for managing distributed test runs in Kubernetes
icon: https://avatars.githubusercontent.com/u/2641063?s=200&v=4
type: application
version: 0.1.9
appVersion: "0.1.5"
